# Generated by Django 4.1.5 on 2023-09-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traditional_product_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
